import 'package:flutter/material.dart';
import '../utils/app_colors.dart';

class TermsAndConditionsScreen extends StatelessWidget {
  const TermsAndConditionsScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms & Conditions'),
        flexibleSpace: Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              colors: [
                AppColors.deepEmerald,
                AppColors.deepEmerald,
              ],
            ),
          ),
        ),
        foregroundColor: AppColors.cardDark,
        elevation: 0,
      ),
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Colors.grey.shade50,
              AppColors.cardDark,
            ],
          ),
        ),
        child: ListView(
          padding: const EdgeInsets.all(20),
          children: [
            _buildHeader(),
            const SizedBox(height: 24),
            _buildSection(
              'WELCOME TO NIKKAH MATCH',
              [
                'This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
                'This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and the terms and conditions for access or usage of Nikkah Match.',
                'Nikkah Match is a newly launched platform (2026) focused on building a trusted community of sincere matrimony seekers. As a growing platform, we prioritise authentic connections and quality matches over quantity. We are committed to keeping scammers and fake profiles away using the best-in-class verification features.',
                'Please read the terms of use for this website carefully. By signing up the service, you give your acceptance to be bound by the Terms and conditions herein referred as the "Agreement".',
                'To become a member of this platform and to be able to communicate with fellow members, you must register as a member and follow the instructions given during the Registration process.',
                'This Agreement outlines the terms that you are subjected to as a member of this platform. The Agreement may be revised from time to time at the sole discretion of Nikkah Match and will be intimated to you. Pursuant to such changes, if you continue to use the platform then it will be constituted as your acceptance for the changes.',
                'The Nikkah Match platform is only to facilitate personal advertisement for lawful marriage alliance between persons who are legally competent to enter into matrimony under the laws to which they are subject.',
              ],
            ),
            _buildSection(
              'SCOPE',
              [
                'You understand and acknowledge that Nikkah Match acts as an "Intermediary" as defined under clause (1) sub-clause (w) of Section 2 of the Information Technology Act, 2000.',
                'Nikkah Match is a personalized match making service, which is valid for a period of the applicable package chosen by you from the date of taking the Nikkah Match package. Nikkah Match is an endeavour to help you find your better half (prospect) through the process of searching, short listing and contacting prospects, during the tenure.',
                'Nikkah Match acts as a platform to enable any user to themselves register on it to voluntarily search for profile(s) from the database of Nikkah Match\'s already registered users, for seeking prospective lawful matrimonial alliances for themselves.',
                'You must have a valid/operational mobile phone number and an email id to register. Members are provided with free/paid access for searching profiles from the database as per the partner preference set by you.',
              ],
            ),
            _buildSection(
              'ELIGIBILITY',
              [
                'Nikkah Match membership and rights of admission is reserved solely for Indian Nationals & Citizens, Persons of Indian Origin (PIO), Non Resident Indians (NRI), Persons of Indian Descent or Indian Heritage, and Persons who intend to marry persons of Indian Origin.',
                'You confirm that you are 18 years or above (if you are a woman) or 21 years or above (if you are a man).',
                'If you have applied for Divorce, you may register by stating "Awaiting Divorce".',
                'If you are a resident of any other Country, you are legally competent to marry as per the local rules applicable to your country and you shall comply with the Indian laws for marrying a person of Indian Origin.',
                'In case you are a registrant of the prospective bride/bridegroom and have created a profile on their behalf, you confirm that you have taken their consent for their profile creation.',
              ],
            ),
            _buildSection(
              'REGISTRATION',
              [
                'Registration presumes that the users have read, understood and accepted the terms and conditions.',
                'You shall complete the online registration process with honesty in furnishing true, accurate, current, and complete information with recent photos of you.',
                'Nikkah Match reserves the right to block the registration of your profile if your contact details are mentioned in restricted fields or if there are errors in any data entered.',
                'You acknowledge and confirm that your registration and usage of Nikkah Match services is with the intention of marriage and not otherwise.',
                'Registration of duplicate profiles of the same person is not allowed. Nikkah Match shall have full right to suspend or terminate (without any notice) such duplicate profile.',
              ],
            ),
            _buildSection(
              'ACCOUNT SECURITY',
              [
                'Nikkah Match does not ask for your password and you are cautioned not to share your password with any person.',
                'You are responsible for safeguarding the confidentiality of your login credentials such as your user id, password, OTP, etc.',
                'You agree to accept responsibility for all activities that occur over your account.',
                'This platform does not encourage and/or promote illegitimate sexual relations or affairs outside marriage. If any member is found to be using this platform for such purposes, the membership will be terminated without any refund.',
              ],
            ),
            _buildSection(
              'PROFILE VISIBILITY',
              [
                'By becoming a member of Nikkah Match, you acknowledge that your information will be used solely within the Nikkah Match platform to find suitable matches.',
                'You can control your profile visibility through the profile settings under "Profile Display" options.',
                'Your control over profile visibility is our commitment to ensuring your preferences are respected.',
              ],
            ),
            _buildSection(
              'ROLE AND RESPONSIBILITY OF NIKKAH MATCH',
              [
                'Nikkah Match acts as a mediator and provides an interface to its registered members to search for their prospect.',
                'Nikkah Match cannot guarantee or assume responsibility for any specific results from the use of the data available from the service.',
                'The profile search and matches shown are automatically generated based on the partner preference set by you.',
                'We cannot guarantee the complete protection of user data while it is in transit, or prevent any tampering of the data by a third party with malicious intent before the data reaches our servers.',
                'Nikkah Match does not prohibit any member from sending interest to your profile or communicating with you based on their partner preference. You have the freedom to deny their interest or proceed further if you are interested.',
              ],
            ),
            _buildSection(
              'ROLE AND RESPONSIBILITY OF MEMBER',
              [
                'To get better responses, members are expected to provide a latest photograph which should not be more than 3 (three) months old.',
                'Members are advised to refrain from entering into any financial transactions with prospects. Members shall not seek or provide financial help from/to other members.',
                'Using abusive language when communicating with another person is considered a violation of terms and conditions.',
                'Members agree to regularly log in to their profile and express interest to get effective search results.',
                'If the member fails to update any change in the particulars furnished in their profile, the membership may be suspended.',
                'In case of finalisation of marriage, members shall delete their profile or inform customer care for removal/deletion of their profile.',
                'You will not post or transmit any content that is abusive, obscene, sexually oriented or against national interest.',
                'Use of Bots, EXE\'s, CGI or any other programs/scripts to view content or communicate with Nikkah Match and/or its Members is restricted.',
              ],
            ),
            _buildSection(
              'CUSTOMER CARE / CUSTOMER SERVICE',
              [
                'If there is any need to reach us across any concerns in our service, please feel free to contact us:',
                'Email: support@nikkahmatch.com',
                'Response Time: Within 48 hours',
              ],
            ),
            _buildSection(
              'PRIVACY OF MEMBERSHIP',
              [
                'Please read and follow our Privacy Policy which also governs your visit to Nikkah Match.',
                'The personal information/data provided to us by you during the course of usage will be treated as confidential and in accordance with the Privacy Policy and applicable laws and regulations.',
                'If you object to your information being transferred or used, please do not use the platform.',
              ],
            ),
            _buildSection(
              'EXCHANGE OF INFORMATION FOR CHAT & OTHER SERVICES',
              [
                'All information, data, text, video, messages or other materials, whether publicly or privately transmitted/posted, is the sole responsibility of the person from where such content originated.',
                'Sending lewd, obscene or offensive content using the chat is strictly prohibited.',
                'Using the services in a manner which is meant to be offensive to others shall render the user liable for prosecution under the existing laws as applicable.',
              ],
            ),
            _buildSection(
              'CONFIDENTIALITY',
              [
                'Nikkah Match will maintain the confidentiality of all personal information other than that meant for sharing with the prospect.',
                'Nikkah Match shall take all possible steps for maintaining the confidentiality.',
                'Nikkah Match may disclose such information if required by law without prior intimation to you.',
              ],
            ),
            _buildSection(
              'GRIEVANCE CELL',
              [
                'The Grievance Officer shall handle complaints in relation to breach by the User of computer resource.',
                'In the event you come across any breach by another user including but not limited to having content that is obscene, grossly offensive, harming minors, infringing copyright, etc., please contact us:',
                'Email: support@nikkahmatch.com',
              ],
            ),
            _buildSection(
              'MEDIUM OF COMMUNICATION TO MEMBERS',
              [
                'Member hereby consents for receiving communication including promotional communications through any medium of communications such as electronic mails, calls, SMS or through WhatsApp messages from Nikkah Match.',
                'Nikkah Match by its automatic system sends to its member(s) profile(s) of the prospect by way of images/documents/messages/links.',
                'Member confirms that the mobile number submitted is not registered with the Do Not Disturb / National Customer Preference Register.',
                'You may opt for not getting any call/sms by ticking the appropriate box in the settings.',
              ],
            ),
            _buildSection(
              'DISPUTES BETWEEN MEMBERS',
              [
                'Members are solely responsible for the communications (through any medium) with a prospect or vice versa.',
                'Nikkah Match expressly disclaims any responsibility or liability for any monetary transaction(s) or exchange(s) or interaction(s) between members.',
              ],
            ),
            _buildSection(
              'CONTENT RIGHT',
              [
                'You alone are responsible and liable for the content you provided on our platform including profile details, photograph and other content(s).',
                'You hereby represent and warrant that you own all rights, title, and interest in your content/information or have the required licenses and permissions.',
                'By submitting the content/information, you grant Nikkah Match a worldwide, nonexclusive, royalty-free license to use, reproduce, distribute, and display the content for the purpose of providing our services.',
                'If the content/information is found not to be in compliance with these Terms, Nikkah Match may delete the content and/or terminate or suspend your registration without a refund.',
              ],
            ),
            _buildSection(
              'THIRD PARTY WEBSITES',
              [
                'Nikkah Match may allow third parties to provide services on the platform and may collect payment for such third party services.',
                'In no event shall Nikkah Match be liable to you for such third party services.',
                'Nikkah Match reserves the right to add/delete/alter/modify/suspend any or all services at any time as it may deem fit, without notice.',
              ],
            ),
            _buildSection(
              'LIMITATION OF LIABILITY',
              [
                'The exchange of profile(s) through Nikkah Match should not in any way be construed as a matrimonial offer and/or recommendation and/or advice or guarantee given to the member.',
                'Nikkah Match shall not be liable to you or any third individual for any indirect, considerable, incidental, special or punitive damages, including lost profits arising from your use of the platform.',
                'Our total liability shall not exceed the amount you paid in the last 6 months.',
              ],
            ),
            _buildSection(
              'INDEMNITY',
              [
                'You agree to defend, indemnify, and hold harmless Nikkah Match, its subsidiaries, affiliates, directors, officers, agents, and other partners and employees, from any loss, liability, claim, or demand, including reasonable attorney\'s fees, made by any person through improper use of the service.',
                'This defence and indemnification obligation will survive in perpetuity.',
              ],
            ),
            _buildSection(
              'TERMINATION',
              [
                'If Nikkah Match receives any complaint against you and consequently we have suspended/deleted your profile in good faith, we shall not be responsible to you in any manner whatsoever.',
                'Upon termination/suspension of membership, your right to use or access the platform will cease immediately.',
                'All provisions of these terms and conditions that by their nature should survive termination shall endure termination.',
              ],
            ),
            _buildSection(
              'JURISDICTION AND APPLICABLE LAW',
              [
                'The members unconditionally agree that all disputes and/or differences if any shall be governed by the Laws of India.',
                'The registration of membership and all services are deemed to have been entered into within the territorial jurisdiction of Kerala, India.',
                'Courts in Kerala, India shall have exclusive jurisdiction.',
              ],
            ),
            _buildSection(
              'MODE OF PAYMENT',
              [
                'Nikkah Match uses third party payment gateways for collection of payment through credit/debit cards or other payment instruments.',
                'Activation of paid service shall be subject to the realisation of the said payment.',
                'Payment shall be in accordance with the prevailing RBI guidelines.',
              ],
            ),
            _buildSection(
              'REFUND AND ASSIGNMENT',
              [
                'Member shall not assign or transfer your membership to any other person or entity.',
                'The payments made by any member by way of membership/renewal fee are treated as non-refundable.',
              ],
            ),
            _buildSection(
              'FORCE MAJEURE',
              [
                'Nikkah Match shall have no liability to you for any interruption or delay in access to the platform irrespective of the cause.',
                'The platform does not take any responsibility for the error, deletion, omissions, interruptions, and delay in the process of transactions, line failures in communication, theft or unauthorised access to any information of a member/visitor.',
                'The services provided are available in the AS-IS form.',
              ],
            ),
            _buildSection(
              'ADDITIONAL TERMS FOR NON-RESIDENT INDIAN CUSTOMERS',
              [
                'Jurisdiction: Laws of India shall be applicable.',
                'Arbitration of Disputes: The Parties shall discuss among themselves and resolve any disputes informally. If the dispute is not resolved within 30 days, then such dispute may only be resolved through individual arbitration conducted in accordance with the provisions of The Arbitration and Conciliation Act, 1996, by a sole arbitrator. The seat of Arbitration shall be Kerala, India.',
                'Enforcement: Any proceeding to enforce this arbitration agreement may be brought in Courts of Kerala, India.',
              ],
            ),
            const SizedBox(height: 30),
            _buildAcceptanceText(),
            const SizedBox(height: 30),
          ],
        ),
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.deepEmerald,
            AppColors.deepEmerald,
          ],
        ),
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: AppColors.deepEmerald.withOpacity(0.3),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          Container(
            width: 90,
            height: 90,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: AppColors.cardDark,
              border: Border.all(
                color: AppColors.primaryCyan,
                width: 3,
              ),
              boxShadow: [
                BoxShadow(
                  color: AppColors.primaryCyan.withOpacity(0.3),
                  blurRadius: 15,
                ),
              ],
            ),
            padding: const EdgeInsets.all(12),
            child: Image.asset(
              'assets/images/nikkah_match_app_logo.png',
              fit: BoxFit.contain,
            ),
          ),
          const SizedBox(height: 12),
          const Text(
            'Terms & Conditions',
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.w500,
              color: AppColors.cardDark,
            ),
          ),
          SizedBox(height: 8),
          Text(
            'Last Updated: June 2026',
            style: TextStyle(
              fontSize: 14,
              color: Colors.white70,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSection(String title, List<String> points) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.cardDark,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.white70.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                    colors: [
                      AppColors.deepEmerald,
                      AppColors.deepEmerald,
                    ],
                  ),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Icon(
                  Icons.description_outlined,
                  size: 20,
                  color: AppColors.cardDark,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  title,
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: AppColors.deepEmerald,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),
          ...points.map((point) => Padding(
            padding: const EdgeInsets.only(bottom: 8),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  margin: const EdgeInsets.only(top: 6, right: 8),
                  width: 6,
                  height: 6,
                  decoration: BoxDecoration(
                    color: AppColors.deepEmerald,
                    shape: BoxShape.circle,
                  ),
                ),
                Expanded(
                  child: Text(
                    point,
                    style: TextStyle(
                      fontSize: 14,
                      color: Colors.grey.shade700,
                      height: 1.5,
                    ),
                  ),
                ),
              ],
            ),
          )),
        ],
      ),
    );
  }

  Widget _buildAcceptanceText() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppColors.deepEmerald.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: AppColors.deepEmerald.withOpacity(0.3),
          width: 2,
        ),
      ),
      child: Row(
        children: [
          Icon(
            Icons.info_outline,
            color: AppColors.deepEmerald,
            size: 24,
          ),
          SizedBox(width: 12),
          Expanded(
            child: Text(
              'By using this Platform, you acknowledge that you have read these Terms and Conditions in full and agree to be bound by them.',
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w500,
                color: AppColors.deepEmerald,
                height: 1.5,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
